name: Publish Design Tokens to GitHub Packages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows checking out code
      packages: write # Allows publishing to GitHub Packages
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Set the registry to GitHub Packages for publishing
          registry-url: 'https://npm.pkg.github.com'
          # Use the secret for authentication
          scope: '@barihari' # IMPORTANT: Match your package.json scope
      
      - name: Install Dependencies
        run: npm ci
        
      - name: Publish Package
        run: npm publish
        env:
          # This token is automatically created by GitHub Actions for the repo
          # It must have the 'write:packages' scope set in your repo secrets (NPM_TOKEN)
          NODE_AUTH_TOKEN: ${{ secrets.NPM_Token }} 
